ALL = sender1 receiver1 sender2 receiver2 sender3 receiver3

all: $(ALL)
sender1: sender1.c
receiver1: receiver1.c
sender2: sender2.c
receiver2: receiver2.c
sender3: sender3.c
receiver3: receiver3.c

.PHONY: clean
clean:
	-rm $(ALL)
